### ISSUE TITLE
Guides says interact with bottom right picture block to set images, however it seems only the bottom left allows that.

### ISSUE THREAD

**Issue by wolfsprite** [HashiCraft/fabric-projector-mod#4]
First off, awesome mod.

Main issue, the guide states "In the instance of a connected picture blocks, only the bottom right hand picture block can be used for setting the images.".

However, was not able to get that to work, and after trying every connected block, realized that it was the bottom left.

Tried it with a couple different setups and it was always the bottom left that allowed setting images, bottom right had no affect.

**Comment by nicholasjackson** [comment]
Oh sorry @baphomutt you are correct it is bottom left. I have a new version that makes this mod much easier to use, the jars are in the releases but I need to update the docs.
